USE AdventureWorks2012
GO
-- Sample Query
SELECT * 
	FROM Sales.SalesPerson
GO
-- Use Estimated Execution Plan CTRL + L
	--  Estimated says clustered index scan
/***********************************************************************************************************************************
***********************************************************************************************************************************/

-- Logical and Physical Mapping and query cost
SELECT *
FROM Sales.SalesPerson sp
INNER JOIN Sales.SalesPersonQuotaHistory spq
	ON sp.BusinessEntityID = spq.BusinessEntityID
ORDER BY sp.SalesQuota
GO
-- Logical Operator Inner Join is actually Physical Operator Nested Loop
/***********************************************************************************************************************************
***********************************************************************************************************************************/

-- Alternate Plan Generated by Query Hint
SELECT *
FROM Sales.SalesPerson sp
INNER HASH JOIN Sales.SalesPersonQuotaHistory spq
	on sp.BusinessEntityID = spq.BusinessEntityID
ORDER BY sp.SalesQuota
GO
-- HASH Match = use each row from the top input to build a hash table, and each row from the bottom input to probe into the hash table, outputting all matching rows
	-- Physical Operation	= Hash Match
	-- Logical Operation	= Inner Join
-- Given an explicit hint comparing the above two queries results in an additional cost to execute the query (38% vs 62%)
